mics_data: C:/Users/lschmitz/OneDrive - DIW Berlin/malawi-education-risk-diagnostic/data/raw/MICS6
  2019-2020/Malawi MICS6 SPSS Datasets/Malawi MICS6 SPSS Datasets/fs.sav
mics_gis: C:/Users/lschmitz/OneDrive - DIW Berlin/malawi-education-risk-diagnostic/data/raw/MICS6
  2016-2020 GPS/MWI_2019_MICS_v01_M
ihs_data: ~
